name: Test_Deploy
on: push
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Linting
              run: npm run lint
            - name: Testing
              run: npm run test
            - name: Build Project
              run: npm run build
            - name: Deploying
              run: echo "Deploying!!"
