name: Test_Deploy
on: [push, workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Install dependencies
              uses: npm ci
            - name: Linting
              run: npm run lint
            - name: Testing
              run: npm run test
            - name: Build Project
              run: npm run build
            - name: Deploying
              run: echo "Deploying!!"
