name: Stage Wise Deploy
on: workflow_dispatch
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm ci
            - name: Linting 
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm ci
            - name: Testing
              run: npm run test
    
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm ci
            - name: Deploy
              run: echo "Deployed"